prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}

grafana:
  enabled: true
  adminPassword: admin

  dashboards:
    default:
      pdf-service-dashboard:
        json: |
          {
            "annotations": {
              "list": []
            },
            "editable": true,
            "panels": [
              {
                "title": "Request Processing Time",
                "type": "graph",
                "targets": [
                  {
                    "expr": "rate(request_processing_duration_seconds_sum[5m]) / rate(request_processing_duration_seconds_count[5m])",
                    "legendFormat": "Average processing time"
                  }
                ]
              },
              {
                "title": "PDF Conversion Errors",
                "type": "graph",
                "targets": [
                  {
                    "expr": "pdf_conversion_errors",
                    "legendFormat": "Errors"
                  }
                ]
              },
              {
                "title": "Memory Usage",
                "type": "graph",
                "targets": [
                  {
                    "expr": "memory_usage_bytes",
                    "legendFormat": "Memory"
                  }
                ]
              }
            ]
          }

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
    receivers:
    - name: 'null' 